### PR TITLE
The isLocked method throws a FileNotFoundException on Windows if the file is locked

### PR DESCRIPTION
**Pull request by akkie**
On Windows 7, the `isLocked ` method throws a `FileNotFoundException` if the file is locked by another process.

```
java.io.FileNotFoundException: C:\Users\...\files\import\7601.17514.101119-1850_x64fre_server_eval_de-de-GRMSXEVAL_DE_DVD.iso (The process cannot access the file because it is being used by another process.)
        at java.io.RandomAccessFile.open0(Native Method)
        at java.io.RandomAccessFile.open(Unknown Source)
        at java.io.RandomAccessFile.<init>(Unknown Source)
        at better.files.File.newRandomAccess(File.scala:306)
        at better.files.File.usingLock(File.scala:498)
        at better.files.File.isLocked(File.scala:489)
        at better.files.File.isWriteLocked(File.scala:504)
        at actors.FileImportWorker.actors$FileImportWorker$$handleCreatedFile(FileImportWorker.scala:40)
        at actors.FileImportWorker$$anonfun$receive$1.applyOrElse(FileImportWorker.scala:26)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
```

The `isLocked` method should catch the `FileNotFoundException` and check the existence of a file, because if the file exists, it's clear that the exception doesn't refer to a not existing file.

### CODE REVIEW

**Comment by pathikrit** [comment]
@akkie : Can you verify this - https://github.com/pathikrit/better-files/commit/00f27867ebd0cddec1ace7835dcc2375869fb3ae

**Comment by akkie** [comment]
@pathikrit This will not work, because you must use `exists` and `notExists` in combination to check for the existence of a file.

`exists` means it exists
`!notExists` means it exists because it doesn't not exists (double negative)

Sometimes `exists` returns false even if the file exists. So in this case you must check with `!notExists` for the existence.

**Comment by pathikrit** [comment]
>  This will not work

Are you talking about `def verifiedExists` part will not work OR are you saying that `case _: FileNotFoundException if verifiedExists(linkOptions).isDefined => true` will not work??

**Comment by akkie** [comment]
The case will not work. The `verifiedExists` method will return `Some` if a file exists and it returns `Some` if a file not exists. And in the case you check if the return from the  `verifiedExists` method is `Some`. As boolean expression this would mean `exists || notExists` but you need  `exists || 
!notExists`.

**Comment by akkie** [comment]
You could keep the `verifiedExists` as it is and change the case to:

```scala
case _: FileNotFoundException if verifiedExists(linkOptions).contains("true") || verifiedExists(linkOptions).isEmpty => true
```

Because `!notExists` is `None` in your case.

Or better:
```scala
case _: FileNotFoundException if verifiedExists(linkOptions).getOrElse(true) => true
```

You could also do:
```scala
case _: FileNotFoundException => verifiedExists(linkOptions).getOrElse(true)
```
But this could be error prone if you must check for another `FileNotFoundException `.

**Comment by pathikrit** [comment]
@akkie : That is much cleaner! Thank you. See this: https://github.com/pathikrit/better-files/commit/5ded727e91dc5d6e3574587b0c410cec06bd4037

**Pull request merged**
