### PR TITLE
Migrate to CircleCI 2.0

### PR DESCRIPTION
**Pull request by aa8y**
* Migrates the existing CircleCI build from 1.0 to 2.0. [This guide](https://circleci.com/docs/2.0/migrating-from-1-2/) was used as reference.
* Also comments out CI-specific tests which get canceled (with `FileSpec.this.isCI was false`) when they're locally run. This is done as in 2.0 the tests now run inside Docker containers which should have the same behavior as local runs.

### CODE REVIEW

**Comment by aa8y** [comment]
@pathikrit Let me know if you need me to do anything to help merge this.

**Comment by pathikrit** [comment]
Thanks for the contribution. Can you simply restore the tests commented out instead of deleting them. LGTM otherwise and I will merge.

**Comment by aa8y** [comment]
@pathikrit It's done. Let me know if you had something else in mind.

**Comment by pathikrit** [comment]
@aa8y: Why is 2 builds being triggered in Circle CI???https://circleci.com/gh/pathikrit/better-files
1st passes; 2nd fails. Please help!

**Comment by aa8y** [comment]
Sorry  about that @pathikrit. Didn't mean to break it. I did not have access to the second step of the CI workflow. Therefore I couldn't really test it. But looks like another PR fixed it! If you need anything else I can definitely look at it this weekend.

**Comment by pathikrit** [comment]
Yup it got fixed. Thanks!

**Pull request merged**
