### PR TITLE
Scala 2.13.0 GA

### PR DESCRIPTION
**Pull request by marcospereira**

### CODE REVIEW

**Comment by marcospereira** [comment]
Closing and reopening so Travis can build it.

**Comment by marcospereira** [comment]
Thanks for merging, @pathikrit. Do you have an idea of when a release will be made?

**Comment by pathikrit** [comment]
I am getting this error when I try to release:
```
> sbt ++2.13.0 release

[info] Loading settings for project global-plugins from idea.sbt,metals.sbt ...
[info] Loading global plugins from /Users/pathikrit/.sbt/1.0/plugins
[info] Updating ProjectRef(uri("file:/Users/pathikrit/.sbt/1.0/plugins/"), "global-plugins")...
[info] Done updating.
[info] Loading settings for project better-files-build from plugins.sbt ...
[info] Loading project definition from /Users/pathikrit/workspace/better-files/project
[info] Updating ProjectRef(uri("file:/Users/pathikrit/workspace/better-files/project/"), "better-files-build")...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Loading settings for project root from version.sbt,build.sbt ...
[info] Set current project to better-files-root (in build file:/Users/pathikrit/workspace/better-files/)
[info] Setting Scala version to 2.13.0 on 3 projects.
[info] Reapplying settings...
[info] Set current project to better-files-root (in build file:/Users/pathikrit/workspace/better-files/)
[info] Updating core...
[info] Done updating.
[info] Updating akka...
[info] Done updating.
Release version [3.8.1] : 3.8.0
Next version [3.8.1-SNAPSHOT] :
[info] Setting version to '3.8.0'.
[info] Reapplying settings...
[info] Set current project to better-files-root (in build file:/Users/pathikrit/workspace/better-files/)
Tag [v3.8.0] exists! Overwrite, keep or abort or enter a new tag (o/k/a)? [a] o
[warn] Overwriting a tag can cause problems if others have already seen the tag (see `git help tag`)!
[info] Reapplying settings...
[info] Set current project to better-files-root (in build file:/Users/pathikrit/workspace/better-files/)
[info] Updating core...
[info] Wrote /Users/pathikrit/workspace/better-files/core/target/scala-2.13/better-files_2.13-3.8.0.pom
[info] Done updating.
[info] Wrote /Users/pathikrit/workspace/better-files/akka/target/scala-2.13/better-files-akka_2.13-3.8.0.pom
[info] Updating akka...
[info] Main Scala API documentation to /Users/pathikrit/workspace/better-files/core/target/scala-2.13/api...
[info] Done updating.
[info] Main Scala API documentation to /Users/pathikrit/workspace/better-files/akka/target/scala-2.13/api...
model contains 11 documentable templates
[info] Main Scala API documentation successful.
[info] Packaging /Users/pathikrit/workspace/better-files/akka/target/scala-2.13/better-files-akka_2.13-3.8.0-javadoc.jar ...
[info] Done packaging.
[error] gpg: Warning: not using '0x66aa02ec8aa60db9' as default key: No secret key
[error] gpg: all values passed to '--default-key' ignored
[error] gpg: no default secret key: No secret key
[error] gpg: signing failed: No secret key
[warn] there were two deprecation warnings (since 2.13.0); re-run with -deprecation for details
[warn] there were 8 feature warnings; re-run with -feature for details
model contains 72 documentable templates
[warn] two warnings found
[info] Main Scala API documentation successful.
[info] Packaging /Users/pathikrit/workspace/better-files/core/target/scala-2.13/better-files_2.13-3.8.0-javadoc.jar ...
[info] Done packaging.
[error] gpg: Warning: not using '0x66aa02ec8aa60db9' as default key: No secret key
[error] gpg: all values passed to '--default-key' ignored
[error] gpg: no default secret key: No secret key
[error] gpg: signing failed: No secret key
[error] java.lang.RuntimeException: Failure running 'gpg --no-default-keyring --keyring /Users/pathikrit/.gnupg/pubring.kbx --detach-sign --armor --default-key 0x66aa02ec8aa60db9 --output /Users/pathikrit/workspace/better-files/core/target/scala-2.13/better-files_2.13-3.8.0.pom.asc /Users/pathikrit/workspace/better-files/core/target/scala-2.13/better-files_2.13-3.8.0.pom'.  Exit code: 2
[error]         at scala.sys.package$.error(package.scala:26)
[error]         at com.typesafe.sbt.pgp.CommandLineGpgSigner.sign(PgpSigner.scala:28)
[error]         at com.typesafe.sbt.pgp.PgpSettings$.$anonfun$signingSettings$2(PgpSettings.scala:158)
[error]         at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:240)
[error]         at scala.collection.immutable.Map$Map4.foreach(Map.scala:233)
[error]         at scala.collection.TraversableLike.flatMap(TraversableLike.scala:240)
[error]         at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:237)
[error]         at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
[error]         at com.typesafe.sbt.pgp.PgpSettings$.$anonfun$signingSettings$1(PgpSettings.scala:155)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] java.lang.RuntimeException: Failure running 'gpg --no-default-keyring --keyring /Users/pathikrit/.gnupg/pubring.kbx --detach-sign --armor --default-key 0x66aa02ec8aa60db9 --output /Users/pathikrit/workspace/better-files/akka/target/scala-2.13/better-files-akka_2.13-3.8.0.pom.asc /Users/pathikrit/workspace/better-files/akka/target/scala-2.13/better-files-akka_2.13-3.8.0.pom'.  Exit code: 2
[error]         at scala.sys.package$.error(package.scala:26)
[error]         at com.typesafe.sbt.pgp.CommandLineGpgSigner.sign(PgpSigner.scala:28)
[error]         at com.typesafe.sbt.pgp.PgpSettings$.$anonfun$signingSettings$2(PgpSettings.scala:158)
[error]         at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:240)
[error]         at scala.collection.immutable.Map$Map4.foreach(Map.scala:233)
[error]         at scala.collection.TraversableLike.flatMap(TraversableLike.scala:240)
[error]         at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:237)
[error]         at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
[error]         at com.typesafe.sbt.pgp.PgpSettings$.$anonfun$signingSettings$1(PgpSettings.scala:155)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (core / signedArtifacts) Failure running 'gpg --no-default-keyring --keyring /Users/pathikrit/.gnupg/pubring.kbx --detach-sign --armor --default-key 0x66aa02ec8aa60db9 --output /Users/pathikrit/workspace/better-files/core/target/scala-2.13/better-files_2.13-3.8.0.pom.asc /Users/pathikrit/workspace/better-files/core/target/scala-2.13/better-files_2.13-3.8.0.pom'.  Exit code: 2
[error] (akka / signedArtifacts) Failure running 'gpg --no-default-keyring --keyring /Users/pathikrit/.gnupg/pubring.kbx --detach-sign --armor --default-key 0x66aa02ec8aa60db9 --output /Users/pathikrit/workspace/better-files/akka/target/scala-2.13/better-files-akka_2.13-3.8.0.pom.asc /Users/pathikrit/workspace/better-files/akka/target/scala-2.13/better-files-akka_2.13-3.8.0.pom'.  Exit code: 2
```

`gpg`:
```
> gpg --list-keys pathikritbhowmick@msn.com

pub   rsa2048 2015-10-15 [SC]
      5E82257FC5B09620C1295D91D8B275D23E219504
uid           [ unknown] Pathikrit Bhowmick <pathikritbhowmick@msn.com>
sub   rsa2048 2015-10-15 [E]

pub   rsa2048 2018-07-24 [SC] [expires: 2020-07-23]
      F5003E5C4718B1F466B244F766AA02EC8AA60DB9
uid           [ unknown] Pathikrit Bhowmick <pathikritbhowmick@msn.com>
sub   rsa2048 2018-07-24 [E] [expires: 2020-07-23]
```

Incidentally I am at ScalaDays - I am sure someone at the conference can help me :)

**Comment by pathikrit** [comment]
@eed3si9n helped me release this https://repo1.maven.org/maven2/com/github/pathikrit/

**Pull request merged**
