### PR TITLE
operator for moving a file atomically

### PR DESCRIPTION
**Pull request by rvanheest**
This PR introduces a new operator that moves a file atomically.

`src moveAtomicallyTo dest`

### CODE REVIEW

**Comment by rvanheest** [comment]
For some reason this failed in Travis due to a download error with SBT. @pathikrit can you retry this build? I've tested it in a couple of projects I'm working on and there it works fine.

**Comment by pathikrit** [comment]
Thank you for the Pull Request! 

In the interest of keeping the API surface small, can we just add an option to the existing `moveTo`?

```scala
  def moveTo(destination: File, overwrite: Boolean = false, atomically: Boolean = false): destination.type = {
    val copyOptions = if (isAtomically) Seq(StandardCopyOption.ATOMIC_MOVE) else File.CopyOptions(overwrite)
    Files.move(path, destination.path, copyOptions: _*)
    destination
  }
```

Thank you!

**Comment by rvanheest** [comment]
Hi @pathikrit, I have tried that in the process of coming up with the current solution as well. However, I wondered what it would mean to say `moveTo(dest, overwrite = true, atomically = true)`? In the [docs](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#move-java.nio.file.Path-java.nio.file.Path-java.nio.file.CopyOption...-) it says: "_The move is performed as an atomic file system operation and **all other options are ignored**._". Hence I wondered whether these two options should be provided simultaniously. After all, as long as `atomically` is set to `true`, the value for `overwrite` doesn't matter. In that case you also shouldn't offer it. This is a trade-off in the API design: do you expand the API with an extra operator or do you offer parameters that have no effect/meaning?

Of course I'll be happy to change the code as suggested by you, but I wanted to put this consideration before you first. Let me know what you think.

**Comment by pathikrit** [comment]
Good point. How about this then:

```scala
 def moveTo(destination: File, copyOptions: File.CopyOptions = File.CopyOptions(overwrite =false)): destination.type = {
    Files.move(path, destination.path, copyOptions: _*)
    destination
  }
```

and we add this in `File.CopyOptions`:
```scala
CopyOptions {
  val atomically: CopyOptions = Seq(StandardCopyOption.ATOMIC_MOVE)
}
```

This way we can call `foo.moveTo(bar, File.CopyOptions.atomically)`?

**Comment by rvanheest** [comment]
Looks great to me as well. However, that would be a breaking change, if you change the method signature of `moveTo`.

Alternatively, an overload is not feasible here, since both the 'old' en 'new' `moveTo` can be called with one argument (default value `false` resp. `File.CopyOptions(overwrite = false)`). A variant where the `CopyOptions` argument is moved to an `implicit` context will have the same problem.

I'll push a solution with the breaking change for now.

**Pull request merged**
